sonar.projectKey=itinerary-service
sonar.projectName=Itinerary Microservice
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/alembic/**,**/tests/**,**/__pycache__/**
